version: '3'
services:
  db:
    image: keinos/sqlite3:latest
    container_name: kanban-sqlite3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    command:
      "postgres -c 'max_connections=500'"
    restart: always

volumes:
  sqlite3_data:
  app-storage:
